name: MoonerSethome
version: 0.2
main: org.mooner.sethome.Main
description: Sethome Plugin
author: Mooner510
api-version: 1.18

commands:
  sethome:
    useage: /sethome
  home:
    useage: /home
  removehome:
    useage: /removehome
    aliases: [delhome]
  back:
    useage: /back
  whisper:
    aliases: [w, msg,tell]
    useage: /w
  reply:
    useage: /r
    aliases: [r]
  tpa:
    useage: /tpa
  tpaccept:
    useage: /tpaccept
  tpcancel:
    useage: /tpcancel
  reloadhome:
#  revive:
#    useage: /revive
#  discordsyntax:
#    useage: /discordsyntax
